### ISSUE TITLE
Idea: Separate Public Key Infrastructure so that citizens know which key to use for encryption

### ISSUE THREAD

**Issue by ramboldio** [LilithWittmann/formularium#16]

**Comment by LilithWittmann** [comment]
Could you please elaborate, why we need a separate PK infrastructure? What kind of security benefits (especially considering that this would mean our users would have to maintain another piece of software) would bring us this over serving the public keys via the backend of formularium?

**Comment by ramboldio** [comment]
Mainly concerned about having sth working that integrates with the broader ecosystem and which can provide public keys to other services without a custom integration. Unfortunately, I don't really now the go to solution.

Will close for now as I think it's not that high of a priority at the current stage.
